### ISSUE TITLE
Update MongoMapper to 0.8.4

### ISSUE THREAD

**Issue by foca** [djsun/sinatra_resource#1]
MongoMapper 0.8.2 was pulled off rubygems.org, so installing this becomes quite the nightmare :)

**Comment by djsun** [comment]
Thanks for letting me know. I'll update.

**Comment by foca** [comment]
We fixed it at http://github.com/cubox/sinatra_resource

**Comment by djsun** [comment]
Thanks. I updated my repository as well. There were also some failing tests that I fixed.
